STRINGS = {
    "en": {
        "welcome":     "Welcome to PostHarvest IQ",
        "select_crop": "Select your crop:",
        "maize":       "Maize",
        "tomatoes":    "Tomatoes",
        "select_dist": "Select your district:",
        "store":       "STORE your crop",
        "sell_now":    "SELL NOW",
        "sell_partial":"SELL PARTIAL",
        "price_rise":  "Expected price rise",
        "net_gain":    "Net gain after storage",
        "nearest":     "Nearest storage",
        "cost":        "cost per bag/month",
        "call":        "Call",
    },
    "dag": {
        "welcome":     "TODO: Dagbani translation",
        "select_crop": "TODO: Dagbani translation",
        "maize":       "TODO: Dagbani translation",
        "tomatoes":    "TODO: Dagbani translation",
        "select_dist": "TODO: Dagbani translation",
        "store":       "TODO: Dagbani translation",
        "sell_now":    "TODO: Dagbani translation",
        "sell_partial":"TODO: Dagbani translation",
        "price_rise":  "TODO: Dagbani translation",
        "net_gain":    "TODO: Dagbani translation",
        "nearest":     "TODO: Dagbani translation",
        "cost":        "TODO: Dagbani translation",
        "call":        "TODO: Dagbani translation",
    },
    "hau": {
        "welcome":     "TODO: Hausa translation",
        "select_crop": "TODO: Hausa translation",
        "maize":       "TODO: Hausa translation",
        "tomatoes":    "TODO: Hausa translation",
        "select_dist": "TODO: Hausa translation",
        "store":       "TODO: Hausa translation",
        "sell_now":    "TODO: Hausa translation",
        "sell_partial":"TODO: Hausa translation",
        "price_rise":  "TODO: Hausa translation",
        "net_gain":    "TODO: Hausa translation",
        "nearest":     "TODO: Hausa translation",
        "cost":        "TODO: Hausa translation",
        "call":        "TODO: Hausa translation",
    }
}