STRINGS = {
    "en": {
        "welcome":      "Welcome to PostHarvest IQ",
        "select_crop":  "Select your crop:",
        "maize":        "Maize",
        "millet":       "Millet",
        "sorghum":      "Sorghum",
        "select_dist":  "Select your district:",
        "store":        "STORE your crop",
        "sell_now":     "SELL NOW",
        "sell_partial": "SELL HALF — STORE HALF",
        "price_rise":   "Expected price rise",
        "net_gain":     "Net gain after storage",
        "nearest":      "Nearest storage",
        "cost":         "Cost per bag/month",
        "call":         "Call",
    },
    "dag": {
        "welcome":      "Ni ti PostHarvest IQ",
        "select_crop":  "Yuli a bɔri di gbana:",
        "maize":        "Kaŋ (Maize)",
        "millet":       "Dawa (Millet)",
        "sorghum":      "Zumaya (Sorghum)",
        "select_dist":  "Yuli a tindana:",
        "store":        "KPAGI ni a gbana",
        "sell_now":     "DI a gbana ziŋ",
        "sell_partial": "DI bani — KPAGI bani",
        "price_rise":   "Ligdi zaai",
        "net_gain":     "Ni gbana kpɛm paai",
        "nearest":      "Kpɛng storage",
        "cost":         "GHS/bag/kpɛm",
        "call":         "Sɔŋ",
    },
    "hau": {
         "welcome":      "Barka da zuwa PostHarvest IQ",
        "select_crop":  "Zaɓi amfanin gona:",
        "maize":        "Masara (Maize)",
        "millet":       "Gero (Millet)",
        "sorghum":      "Dawa (Sorghum)",
        "select_dist":  "Zaɓi gundumar:",
        "store":        "ADANA amfanin gona",
        "sell_now":     "SAYAR YANZU",
        "sell_partial": "SAYAR KASHI — ADANA KASHI",
        "price_rise":   "Tsammanin haɓakar farashi",
        "net_gain":     "Riba bayan adanawa",
        "nearest":      "Kusa da wurin adanawa",
        "cost":         "GHS/jaka/wata",
        "call":         "Kira",
    }
}