STRINGS = {
    "en": {
        "welcome":      "Welcome to PostHarvest IQ",
        "select_crop":  "Select your crop:",
        "maize":        "Maize",
        "millet":       "Millet",
        "sorghum":      "Sorghum",
        "select_dist":  "Select your district:",
        "store":        "STORE your crop",
        "sell_now":     "SELL NOW",
        "sell_partial": "SELL HALF — STORE HALF",
        "price_rise":   "Expected price rise",
        "net_gain":     "Net gain after storage",
        "nearest":      "Nearest storage",
        "cost":         "Cost per bag/month",
        "call":         "Call",
    },
    "dag": {
        # Have a native Dagbani speaker complete these 13 phrases
        "welcome":      "TODO",
        "select_crop":  "TODO",
        "maize":        "Masara",
        "millet":       "TODO",
        "sorghum":      "TODO",
        "select_dist":  "TODO",
        "store":        "KPAGI ni masara",
        "sell_now":     "TODO",
        "sell_partial": "TODO",
        "price_rise":   "TODO",
        "net_gain":     "TODO",
        "nearest":      "TODO",
        "cost":         "TODO",
        "call":         "Sɔŋ",
    },
    "hau": {
        # Have a native Hausa speaker complete these 13 phrases
        "welcome":      "TODO",
        "select_crop":  "Zaɓi amfanin gona:",
        "maize":        "Masara",
        "millet":       "TODO",
        "sorghum":      "TODO",
        "select_dist":  "Zaɓi gundumar:",
        "store":        "ADANA masararka",
        "sell_now":     "TODO",
        "sell_partial": "TODO",
        "price_rise":   "TODO",
        "net_gain":     "Riba",
        "nearest":      "Kusa",
        "cost":         "TODO",
        "call":         "Kira",
    }
}